# Generated by Django 5.1.6 on 2025-02-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsReservas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('active_booking', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=15)),
                ('customer_selection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='clientes.modelsclientes')),
            ],
            options={
                'verbose_name': 'ModelsReserva',
                'verbose_name_plural': 'ModelsReservas',
                'db_table': 'Modelsreservas',
            },
        ),
    ]
