# Generated by Django 5.1.6 on 2025-02-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReserApp', '0002_alter_modelsreservas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsreservas',
            name='date_end',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='modelsreservas',
            name='date_start',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
    ]
