# Generated by Django 5.1.6 on 2025-02-12 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReserApp', '0003_alter_modelsreservas_date_end_and_more'),
        ('alojamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsreservas',
            name='departamento_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Departamento', to='alojamiento.departamentos'),
        ),
        migrations.AddField(
            model_name='modelsreservas',
            name='habitacion_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Habitacion', to='alojamiento.habitaciones'),
        ),
    ]
