# Generated by Django 5.1.6 on 2025-02-12 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReserApp', '0005_remove_modelsreservas_habitacion_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsreservas',
            name='date_create_customer',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelsreservas',
            name='number_nights',
            field=models.IntegerField(default=6, verbose_name='Cantidad de Noches'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelsreservas',
            name='number_people',
            field=models.IntegerField(default=6, verbose_name='Cantidad de personas'),
            preserve_default=False,
        ),
    ]
