# Generated by Django 5.1.6 on 2025-02-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReserApp', '0006_modelsreservas_date_create_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsreservas',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Total'),
        ),
        migrations.AlterField(
            model_name='modelsreservas',
            name='active_booking',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada')], default='pendiente', max_length=15),
        ),
    ]
