# Generated by Django 5.1.6 on 2025-02-19 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReserApp', '0007_modelsreservas_price_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsreservas',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Pagado'),
        ),
        migrations.AlterField(
            model_name='modelsreservas',
            name='number_nights',
            field=models.IntegerField(verbose_name='N°. Noches'),
        ),
        migrations.AlterField(
            model_name='modelsreservas',
            name='number_people',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Cantidad de personas'),
        ),
        migrations.AlterField(
            model_name='modelsreservas',
            name='price_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Total'),
        ),
    ]
