# Generated by Django 4.2.16 on 2025-02-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0001_initial'),
        ('clientes', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='customer_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='clientes.modelsclientes'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='department',
            field=models.ManyToManyField(blank=True, to='alojamiento.departamentos'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='alojamiento.habitaciones'),
        ),
    ]
