# Generated by Django 5.1.6 on 2025-02-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alojamiento', '0003_remove_departamentos_max_persons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_temporada', models.CharField(default='Temporada sin nombre', max_length=250)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('dias', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], help_text="Ejemplo: 'LUN,MAR,MIE'", max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('alojamiento', models.ManyToManyField(related_name='alojamiento', to='alojamiento.departamentos')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'db_table': 'Temporadas',
            },
        ),
    ]
