# Generated by Django 5.1.6 on 2025-02-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_booking', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Alojamiento')),
                ('description_booking', models.TextField(max_length=255, verbose_name='Descripción del Alojamiento')),
                ('price_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por noche')),
                ('capacity_booking', models.IntegerField(verbose_name='Capacidad Maxima')),
                ('size_booking', models.CharField(max_length=50, verbose_name='Tamaño del Alojamiento')),
                ('active_booking', models.BooleanField(default=True, verbose_name='Estado del Alojamiento')),
                ('costo_limpieza', models.DecimalField(decimal_places=2, default=50.0, help_text='Costo fijo por servicio de limpieza (S/50.00)', max_digits=10)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_booking', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Alojamiento')),
                ('description_booking', models.TextField(max_length=255, verbose_name='Descripción del Alojamiento')),
                ('price_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por noche')),
                ('capacity_booking', models.IntegerField(verbose_name='Capacidad Maxima')),
                ('size_booking', models.CharField(max_length=50, verbose_name='Tamaño del Alojamiento')),
                ('active_booking', models.BooleanField(default=True, verbose_name='Estado del Alojamiento')),
                ('type_booking', models.CharField(choices=[('Doble', 'Doble'), ('Matrimonial', 'Matrimonial'), ('Triple', 'Triple'), ('Familiar', 'Familiar')], max_length=150, verbose_name='Tipo de habitación')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'db_table': 'Habitaciones',
            },
        ),
    ]
