# Generated by Django 5.1.6 on 2025-02-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentos',
            name='max_persons',
            field=models.IntegerField(default=5, verbose_name='Capacidad Maxima'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='max_persons',
            field=models.IntegerField(default=5, verbose_name='Capacidad Maxima'),
            preserve_default=False,
        ),
    ]
