# Generated by Django 5.1.6 on 2025-02-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0002_departamentos_max_persons_habitaciones_max_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentos',
            name='max_persons',
        ),
        migrations.RemoveField(
            model_name='habitaciones',
            name='max_persons',
        ),
    ]
